version: '3.2'
services:
  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_TAG}
    ports:
    - 9093:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
    - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus:/etc/prometheus:ro

  hello_all:
    image: hello
    build:
      context: hello
      args:
        goPackage: github.com/zhongzc/alertmanager_playground/hello
        goVersion: 1.15
      cache_from:
      - golang:1.15
      - scratch
  hello_sre:
    image: hello
  hello_user:
    image: hello

  webhook_default:
    image: webhook
    build:
      context: webhook
      args:
        goPackage: github.com/zhongzc/alertmanager_playground/webhook
        goVersion: 1.15
      cache_from:
      - golang:1.15
      - scratch
  webhook_admin:
    image: webhook
  webhook_sre:
    image: webhook
  webhook_user:
    image: webhook
