global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: hello_all
  scrape_interval: 5s
  static_configs:
  - targets:
    - hello_all:2112
- job_name: hello_sre
  scrape_interval: 5s
  static_configs:
  - targets:
    - hello_sre:2112
- job_name: hello_user
  scrape_interval: 5s
  static_configs:
  - targets:
    - hello_user:2112
